### ISSUE TITLE
Is not showing the list of projects and categories 

### ISSUE THREAD

**Issue by KarlyGrCm** [ucoria-itexico/nonova#14]
The command 
`$ python nonova.py -p` and `$ python nonova.py -C`

is not showing any result 🙄 

Also, is showing my email and password after run each command

**Comment by radiotaiso** [comment]
ee2f1c0  

Ya se imprime en consola categorias y proyectos, ya no se imprime el comando y no se ve el password

**Comment by radiotaiso** [comment]
ya estufas dijo mabe
