### ISSUE TITLE
Error when if I add an activity manual in config.ini

### ISSUE THREAD

**Issue by huds79** [ucoria-itexico/nonova#21]
Activity created with id: 119172

invalid argument for flag `-P, --project' (expected int): strconv.ParseInt: parsing "None": invalid syntax
Traceback (most recent call last):
  File "nonova.py", line 148, in <module>
    sys.exit(main())
  File "nonova.py", line 145, in main
    add_from_file()
  File "nonova.py", line 122, in add_from_file
    backend.execute(a.toString())
  File "/Users/developer/nonova/classer.py", line 77, in execute
    output = subprocess.check_output(self.payload, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '/Users/developer/nonova/bin/osx/nova-cli add -P None -t 1 -c 1 Changing branch from master instead RC -u ehudson@itexico.net -p ******' returned non-zero exit status 1

**Comment by radiotaiso** [comment]
Taking a look, and censoring sensitive data 😝

**Comment by radiotaiso** [comment]
Manually adding a new activity seems to be sending `None` under -P (projects)

**Comment by radiotaiso** [comment]
```
def read_from_file():
    file_activities = {}
    activity_values = []
    passes = 1
    novaconf.read(novaconf.args.config)
    for (each_key, each_val) in novaconf.items("Activities"):
        keys = {}
        k, v = each_key.split(" ")
        keys[v] = each_val
        activity_values.append(keys)
        file_activities[k] = activity_values
        if passes == 4:
            activity_values = []
        passes += 1
    return file_activities
```

Turns out number of passes was reseting on 5 pases, changed it to 4, I assume it was expecting ticket.

Fixed on https://github.com/UpsetPelican/nonova/commit/77e9e4eb68ff3d80717c99f5faedf10149d91755
