### ISSUE TITLE
I want to validate input for projects and categories

### ISSUE THREAD

**Issue by radiotaiso** [ucoria-itexico/nonova#22]
Currently when submitting a wrong category or project, nonova freezes and does nothing.
We need a way to prevent that

**Comment by GurgehMorat** [comment]
Agreed. We should also make another ticket to have unit test the backend connection

**Comment by GurgehMorat** [comment]
Let's not close this ticket yet

**Comment by radiotaiso** [comment]
Exception is raised, there, @chaps did it.
https://github.com/UpsetPelican/nonova/commit/ebe0e727463fd45ab8e9f79fbb1ff55dfd23fba2
